export enum WebserverEnum {
    VERSION_DEPRECATED = "Deprecated API version",
    VERSION_INVALID = "Invalid API version",
    INVALID_AUTHORIZATION = "An invalid Authorization was provided",

    ERR_UNKNOWN = "Unknown error occurred",
    ERR_MISSING_QUERY = "Missing query parameter: \"![[query]]\"",
    ERR_MISSING_HEADER = "Missing header: \"![[header]]\"",
    ERR_MISSING_BODY = "Missing body parameter: \"![[body]]\"",
    ERR_WRONG_BODY = "Invalid type \"![[current]]\" for '\"![[body]]\", expected \"![[type]]\"",

    STATUS_400 = "Bad Request",
    STATUS_401 = "Unauthorized",
    STATUS_402 = "Payment Required",
    STATUS_403 = "Forbidden",
    STATUS_404 = "Not Found",
    STATUS_405 = "Method Not Allowed",
    STATUS_406 = "Not Acceptable",
    STATUS_407 = "Proxy Authentication Required",
    STATUS_408 = "Request Timeout",
    STATUS_409 = "Conflict",
    STATUS_410 = "Gone",
    STATUS_411 = "Length Required",
    STATUS_412 = "Precondition Failed",
    STATUS_413 = "Payload Too Large",
    STATUS_414 = "URI Too Long",
    STATUS_415 = "Unsupported Media Type",
    STATUS_416 = "Range Not Satisfiable",
    STATUS_417 = "Expectation Failed",
    STATUS_418 = "I'm a Teapot",
    STATUS_421 = "Misdirected Request",
    STATUS_422 = "Unprocessable Entity",
    STATUS_423 = "Locked",
    STATUS_424 = "Failed Dependency",
    STATUS_425 = "Too Early",
    STATUS_426 = "Upgrade Required",
    STATUS_428 = "Precondition Required",
    STATUS_429 = "Too Many Requests",
    STATUS_431 = "Request Header Fields Too Large",
    STATUS_451 = "Unavailable For Legal Reasons",

    STATUS_500 = "Internal Server Error",
    STATUS_501 = "Not Implemented",
    STATUS_502 = "Bad Gateway",
    STATUS_503 = "Service Unavailable",
    STATUS_504 = "Gateway Timeout",
    STATUS_505 = "HTTP Version Not Supported",
    STATUS_506 = "Variant Also Negotiates",
    STATUS_507 = "Insufficient Storage",
    STATUS_508 = "Loop Detected",
    STATUS_510 = "Not Extended",
    STATUS_511 = "Network Authentication Required",
}